weights_path: "/scratch/cvlab/home/afan/projects/diffusion_hyperfeatures/experiments/6fggjgdc_sdv1-5_1-step_dim-8-256-DTU/checkpoint_step_5000.pt"

# weights_path: "/scratch/cvlab/home/afan/projects/diffusion_hyperfeatures/experiments/iscz5jec_sdv1-5_1-step_dim-8-256/checkpoint_step_4000.pt"

# weights_path: "/scratch/cvlab/home/afan/projects/diffusion_hyperfeatures/experiments/x9qjetpy_sdv1-5_1-step_dim-3-256/checkpoint_step_4000.pt"

# weights_path: "/scratch/cvlab/home/afan/projects/diffusion_hyperfeatures/experiments/12zu9vsq_sdv1-5_50-step_dim-8/checkpoint_step_4000.pt"

# weights_path: "/scratch/cvlab/home/afan/projects/diffusion_hyperfeatures/experiments/hs2jsnyr_sdv1-5_50-step_dim-8-128/checkpoint_step_4000.pt"
load_resolution: 512
batch_size: 5