# weights_path: "/scratch/cvlab/home/afan/projects/diffusion_hyperfeatures/experiments/my10h72w_sdv1-5_50-step_dim-32-128/checkpoint_step_4000.pt"
weights_path: "/scratch/cvlab/home/afan/projects/diffusion_hyperfeatures/experiments/y4ortpmq_sdv1-5_50-step_dim-32-128-DTU/checkpoint_step_5000.pt"

load_resolution: 512
batch_size: 5