# ======== Customize Paths =======
wandb_run: sdv1-5_50-step_dim-32-128-megadepth
wandb_project: dhf
wandb_mode: online
results_folder: experiments
# ======== Data / Logging ========
dataset: megadepth
train_path: /scratch/cvlab/datasets/dataset_DISK
megadepth_batch_size: 1
train_scene_limit: 1000
test_scene_limit: 250
n_pixel_sample: 15
flip_timesteps: False
# ======= Ours (All Steps) =======
save_timestep: [49, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0]
num_timesteps: 50
# ======== Ours - One-Step =======
# save_timestep: [0]
# num_timesteps: 1
# ======= Training Hparams =======
weight_decay: 0
max_epochs: 1
max_steps_per_epoch: 50000
val_every_n_steps: 100
plot_every_n_steps: -1
lr: 1e-3
# ======== Model Hparams =========
projection_dim: 32
num_norm_groups: 4
# ============== SDv1-5 ==========
model_id: runwayml/stable-diffusion-v1-5
# ============== SDv2-1 ==========
# model_id: stabilityai/stable-diffusion-2-1-base
diffusion_mode: inversion
output_resolution: 128
load_resolution: 512
batch_size: 2
prompt: ""
negative_prompt: ""
guidance_scale: -1