# ======== Customize Paths =======
wandb_run: sdv1-5_1-step_dim-8-256-DTU
wandb_project: dhf
wandb_mode: online
results_folder: experiments
# ======== Data / Logging ========
dataset: dtu_yao
train_path: /scratch/cvlab/datasets/dataset_afan/VolRecon/DTU_training
test_path: /scratch/cvlab/datasets/dataset_afan/VolRecon/DTU_training
train_list: /scratch/cvlab/home/afan/projects/2DImageTransform/lists/dtu/train.txt
test_list: /scratch/cvlab/home/afan/projects/2DImageTransform/lists/dtu/val.txt
n_views: 2
n_pixel_sample: 15
flip_timesteps: False
# ======= Ours (All Steps) =======
# save_timestep: [49, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0]
# num_timesteps: 50
# ======== Ours - One-Step =======
save_timestep: [0]
num_timesteps: 1
# ======= Training Hparams =======
weight_decay: 0
max_epochs: 1
max_steps_per_epoch: 20000
val_every_n_steps: 100
plot_every_n_steps: -1
lr: 1e-3
# ======== Model Hparams =========
projection_dim: 8
num_norm_groups: 1
# ============== SDv1-5 ==========
model_id: runwayml/stable-diffusion-v1-5
# ============== SDv2-1 ==========
# model_id: stabilityai/stable-diffusion-2-1-base
diffusion_mode: inversion
output_resolution: 256
load_resolution: 512
batch_size: 2
prompt: ""
negative_prompt: ""
guidance_scale: -1